import Link from "next/link";
import { ArrowLeft, Scale } from "lucide-react";
import { getCurrentUser } from "../../lib/auth";

export default async function TermsPage() {
  const user = await getCurrentUser();

  return (
    <main className="auth-signal min-h-screen px-5 py-6 text-[#123c3a]">
      <nav className="mx-auto flex max-w-4xl items-center justify-between">
        <Link href="/" className="font-signal text-2xl font-black tracking-[-0.08em] transition hover:text-[#6bbf22]">
          CareerLaunch
        </Link>
        <Link href={user ? "/dashboard" : "/login"} className="rounded-full px-4 py-2 text-sm font-black transition hover:bg-[#123c3a] hover:text-[#b9ff66]">
          {user ? "Dashboard" : "Sign in"}
        </Link>
      </nav>

      <article className="mx-auto mt-10 max-w-3xl space-y-8 pb-20">
        <div className="flex items-center gap-4">
          <div className="grid h-14 w-14 place-items-center rounded-full bg-[#b9ff66] text-[#123c3a]">
            <Scale size={26} />
          </div>
          <div>
            <h1 className="font-signal text-5xl font-black uppercase leading-none tracking-[-0.07em]">Terms of Service</h1>
            <p className="mt-2 text-sm font-medium text-[#4b4b4b]">Last updated: July 7, 2026</p>
          </div>
        </div>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">1. Acceptance of Terms</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            By creating an account or using CareerLaunch Studio, you agree to these Terms of Service.
            If you do not agree, do not use the service. These terms may be updated; continued use
            after changes constitutes acceptance.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">2. Service Description</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            CareerLaunch Studio provides resume and cover letter building tools, AI-powered content analysis,
            job matching, and PDF export. The service is provided &quot;as is&quot; during the beta phase,
            with the understanding that features and availability may change.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">3. User Accounts</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            You are responsible for maintaining the confidentiality of your password and for all activities
            under your account. You must provide accurate information. You may not use the service for any
            unlawful purpose or in violation of applicable laws.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">4. Subscriptions & Billing</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            Paid subscriptions are billed monthly through Stripe. You may cancel at any time — access continues
            until the end of the current billing period. Refunds are handled on a case-by-case basis.
            Pricing and plan features may change with notice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">5. AI-Generated Content</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            AI suggestions are generated by third-party models and may contain errors, inaccuracies, or
            fabricated information. You are solely responsible for reviewing and verifying all AI-generated
            content before using it in applications or submissions. We make no guarantees about the accuracy,
            completeness, or suitability of AI-generated suggestions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">6. User Content</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            You retain all rights to the resume content, cover letters, and other documents you create.
            We claim no intellectual property rights over your content. You represent that your content
            does not violate any third-party rights.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">7. Limitation of Liability</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            CareerLaunch Studio is provided &quot;as is&quot; without warranty of any kind. We are not
            liable for any damages arising from your use of the service, including but not limited to
            lost employment opportunities, data loss, or service interruptions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">8. Termination</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            We may suspend or terminate your account for violation of these terms, extended inactivity,
            or if required by law. You may delete your account at any time through the billing page.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="font-signal text-2xl font-black tracking-[-0.04em]">9. Contact</h2>
          <p className="text-sm font-medium leading-7 text-[#4b4b4b]">
            For questions about these terms, contact the account owner.
          </p>
        </section>

        <Link href="/" className="signal-button-light mt-8 inline-flex w-auto">
          <ArrowLeft size={16} /> Back to home
        </Link>
      </article>
    </main>
  );
}
